fix compilation now that SDL2_image is required
resolves:
v_video.o: In function `V_SavePNG':
/home/ryan/git/doomretro/src/v_video.c:1351: undefined reference to `IMG_SavePNG
'
v_video.o: In function `V_Init':
/home/ryan/git/doomretro/src/v_video.c:1284: undefined reference to `IMG_Linked_
Version'
collect2: ld returned 1 exit status
Makefile:55: recipe for target 'doomretro' failed
gmake: *** [doomretro] Error 1